# Generated by Django 6.0.4 on 2026-04-15 15:14

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
