# Generated by Django 6.0.4 on 2026-04-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='compliancerules',
            index=models.Index(fields=['name'], name='contracts_c_name_87d06b_idx'),
        ),
    ]
